package com.bebetab.ui.screens
import androidx.compose.foundation.layout.*;import androidx.compose.foundation.shape.RoundedCornerShape;import androidx.compose.material3.*;import androidx.compose.runtime.*;import androidx.compose.ui.Alignment;import androidx.compose.ui.Modifier;import androidx.compose.ui.platform.LocalContext;import androidx.compose.ui.text.font.FontWeight;import androidx.compose.ui.unit.*;import com.bebetab.data.*;import com.bebetab.ui.components.BebeTabFrame;import com.bebetab.ui.games.*;import kotlinx.coroutines.launch
@Composable private fun currentLanguage():String{val c=LocalContext.current;return remember{ParentSettingsStore(c)}.language.collectAsState(initial="fr").value}
@Composable fun LearnActivityScreen(onBack:()->Unit,onSettings:()->Unit={}){
 val l=currentLanguage();val c=LocalContext.current;val scope=rememberCoroutineScope();val store=remember{ProgressStore(c)}
 BebeTabFrame(if(l=="en")"LEARN" else "APPRENDRE",onBack,onSettings){Row(Modifier.fillMaxSize().padding(4.dp),horizontalArrangement=Arrangement.spacedBy(10.dp)){ContentData.subjects.chunked(4).forEach{row->Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(10.dp)){row.forEach{item->Card(Modifier.weight(1f).fillMaxWidth(),shape=RoundedCornerShape(22.dp)){Column(Modifier.fillMaxSize().padding(10.dp),Alignment.CenterHorizontally,Arrangement.Center){Text(item.emoji,fontSize=30.sp);Text(item.title.text(l),fontSize=18.sp,fontWeight=FontWeight.Black);Text(item.description.text(l),fontSize=10.sp);if(item.id=="letters"||item.id=="numbers")Button(onClick={scope.launch{store.addStars(2)}}){Text("+2 ⭐")}}}}}}}}
}
@Composable fun PlayActivityScreen(onBack:()->Unit,onSettings:()->Unit={}){
 val l=currentLanguage();val c=LocalContext.current;val scope=rememberCoroutineScope();val store=remember{ProgressStore(c)}
 BebeTabFrame(if(l=="en")"PLAY" else "JOUER",onBack,onSettings){Row(Modifier.fillMaxSize().padding(4.dp),horizontalArrangement=Arrangement.spacedBy(10.dp)){Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(10.dp)){ContentData.games.take(4).forEach{GameCard(it,l)}};Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(10.dp)){ContentData.games.drop(4).forEach{item->if(item.id=="memory")MemoryGame{n->scope.launch{store.addStars(n)}}else GameCard(item,l)}}}}
}
@Composable private fun GameCard(item:ActivityContent,l:String){Card(Modifier.fillMaxWidth().height(105.dp),shape=RoundedCornerShape(22.dp)){Row(Modifier.fillMaxSize().padding(12.dp),Alignment.CenterVertically){Text(item.emoji,fontSize=30.sp);Spacer(Modifier.width(10.dp));Column{Text(item.title.text(l),fontSize=19.sp,fontWeight=FontWeight.Black);Text(item.description.text(l),fontSize=11.sp)}}}}
@Composable fun StoryActivityScreen(onBack:()->Unit,onSettings:()->Unit={}){val l=currentLanguage();BebeTabFrame(if(l=="en")"STORIES" else "HISTOIRES",onBack,onSettings){StoryReader(l)}}
@Composable fun MusicActivityScreen(onBack:()->Unit,onSettings:()->Unit={}){val l=currentLanguage();BebeTabFrame(if(l=="en")"MUSIC" else "MUSIQUE",onBack,onSettings){MusicKeyboard(l)}}
@Composable fun DrawActivityScreen(onBack:()->Unit,onSettings:()->Unit={}){val l=currentLanguage();BebeTabFrame(if(l=="en")"DRAW" else "DESSINER",onBack,onSettings){DrawGame(l)}}